spring.application.name=RemittanceAutomation
# ===============================
# SERVER CONFIGURATION
# ===============================
server.port=8080

# ===============================
# ORACLE DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:oracle:thin:@192.168.118.48:1521/POSDB
spring.datasource.username=pos
spring.datasource.password=oracle123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ===============================
# JPA / HIBERNATE CONFIGURATION
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# JWT Security Configuration
application.security.jwt.secret-key=d169552a202ace4ed9b31a326df08noyon3e197a10213030f7c4be596ba99b6
application.security.jwt.expiration=86400000