spring.application.name=RemittanceAutomation
# ===============================
# SERVER CONFIGURATION
# ===============================
server.port=8080

# ===============================
# ORACLE DATABASE CONFIGURATION
# ===============================
spring.datasource.url=***
spring.datasource.username=**
spring.datasource.password=**
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ===============================
# JPA / HIBERNATE CONFIGURATION
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# JWT Security Configuration
application.security.jwt.secret-key=****
application.security.jwt.expiration=86400000